### ISSUE TITLE
[Feat] 메모팅

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#113]
## 설명:
- 메모팅 기능 구현

## TODO:
- [x] - 홈화면 변경 및 추가 사항 적용
- [x] - 과팅 게시판 UI 수정 사항
- [x]  - 메모팅 전체 View/UI
- [x] - 메모 작성 View/UI
- [x] - 메모 작성 Action (메모작성 버튼 클릭및 UITextView 처리)
- [x] - 메모 작성 취소하기 action
- [x] - 메모 등록하기 action/API
- [x] - 메모팅 진행 예/아니요 View/UI
- [x] - 메모 조회 API
- [x] - 메모팅 진행 API/Action - > 해당 채팅 방으로 이동하게끔설정
- [x] - 홈화면 메모팅 남기기 action
