### ISSUE TITLE
UI/View 디자인 수정

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#116]
## 제목:
화면 요소 변경에 따른 디자인 수정
## 설명:
- 새로운 기능 추가로 인한 디자인 수정

## TODO:
- [x] - 신청 현황 디자인 수정
- [x] - 채팅 목록 디자인 수정
- [x] - 행사 관련 View/UI Temp
- [x] - 홈에서 1:1 게시판 클릭 시 토스트 메세지 띄우기: 곧 출시 예정이에요.
