### ISSUE TITLE
오감 총학생회 지누팅 콜라보 기능 API 연결 및 action

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#119]
## 제목:
이벤트성으로 주최하는 기능에 관련 된 API와 action 연결

## 설명:
- 이벤트 전까지는 미오픈 API 연결
- 닉네임을 통한 1대1 신청 API 연결

## TODO:
- [x] - 1. 미오픈/오픈 API
- [x] - 2. 닉네임을 통한 1대1 신청 API 
- [x] - 3. 신청 분기 성공 -> 채팅방 이동 Alert -> 예 입력시 채팅방이동 / 아니요 입력시 유지
- [x] - 4. 신청 분기 실패 -> 실패에 대한 이유 Alert
