### ISSUE TITLE
채팅 목록 관련 기능

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#121]
## 제목:
채팅 목록 관련 기능 API, Design, Action

## 설명:
- 채팅 목록 List 디자인 변경에 따른 기능 변화 API 연동
## TODO:
- [ ] - 채팅 목록 실시간 채팅 메세지, 시간, 새로운메세지 관련 WebSocket Stomp 실시간 통신
- [ ] - 채팅 목록 List 변경
- [ ] - 채팅 목록 List 디자인 변경
