### ISSUE TITLE
테스트 후 수정 사항

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#126]
## 제목:
10.06 피드백 수정 적용하기

## 설명:
피드백 받고 수정해야될 사항 적용 - 총학 관련 및 기능 수정에 따른 1 번째 피드백

## TODO:
- [ ] - 회원가입시 이메일 빈값입력 막기
- [ ] - 회원가입시 한줄소개 null허용
- [x] - 채팅 입력 필드 클릭시 채팅 메세지 리스트도 함께 위로 올리기
- [ ] - 채팅목록리스트 2초간격으로 API 조회
