### ISSUE TITLE
회원가입 네트워크 연동

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#36]
## 설명:
-  회원가입 서버와 연동하기

## TODO:
- [x] - 회원가입 데이터 저장
- [x] - 회원가입시 회원가입 POST API사용
- [x] - 이메일 확인 API
- [x] - 인증번호 확인 로직
- [x] - 이메일,인증번호,비밀번호 확인,닉네임 중복확인에 대한 정규식 구현
