### ISSUE TITLE
채팅 신청 목록 & 신청 받은목록

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#50]
## 제목:
과팅을 진행할 그룹에 채팅 신청 목록 & 신청 받은목록 & 신청현황 디테일

## 설명:
- 과팅 신청 목록/과팅 신청 받은 목록   출력
   -  학과 
   - 이름 
   - 상태

## TODO:
- [x] - 과팅 신청 목록 
- [x] - 과팅 신청 받은 목록 
- [x] - 과팅 신청 현황
- [x] - 거절하기
- [x] - 취소하기
