### ISSUE TITLE
회의를 통한 디자인및 기능 수정

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#58]
## 제목:
회의를 통해 변경된 View/UI 작업

## 설명:
- 회의를 하면서 변경된 화면이나 UI 작업 반영하기

## TODO:
- [x] - 게시물/ 검색 게시물에 인원 표시하기
- [x] - user정보 과|학번|나이로 표시
- [x] - 채팅 신청자는 default로 과팅 멤버 추가하기에 존재, 과팅 멤버추가하기와 검색해서 사용자 추가하는거 상호작용되도록 연결
- [x] - 멤버추가 화면 FullScreen x
- [x] - 과팅 글에서 status가 open이면 채팅 신청 활성화, close이면 채팅 비활성화
