### ISSUE TITLE
[Fix] 피드백 반영

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#70]
## 제목:
전체적으로 피드백 반영하여 수정

## 설명:
- 앱 시연영상을 통한 피드백 전체적으로 수정

## TODO:
- [x] - 비밀번호,인증번호 붙이기
- [x] - 회원가입 1/3 텍스트 있을경우 Button 활성화
- [x] - 버튼 disable Text 흰색
- [x] - 회원가입 1/3 비밀번호 가리기
- [x] - 마이페이지 스크롤 제거
- [x] - 로그인 화면 비밀번호 가리기
- [x] - 홈화면 학과 제목으로 수정
- [x] - 홈화면 환영글 이모티콘 변경하기
