### ISSUE TITLE
전체 알림 설정 기능 추가

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#83]
## 제목:
전체 알림 설정 기능 추가

## 설명:
- 전체 알림 설정 기능 추가를 위한 개발

## TODO:
- [x] - 마이 페이지 구성요소변경
- [x] - 알림 설정 VIew/UI
- [x] - 알림 설정 API
