### ISSUE TITLE
피드백을 통한 에러 사항 및 변경사항 적용

### ISSUE THREAD

**Issue by dongjin97** [GNUting/GNUting-iOS#88]
## 제목:

피드백을 통한 에러 사항 및 변경사항 적용
## 설명:
- 팀원 피드백을 통한 에러사항 및 변경사항 적용

## TODO:
- [x] - 게시물 등록 멘트
- [x] - 내가 쓴 글 들어갔다 나오면 TabBar사라짐 에러 해결
- [x] - 신청형황 Navi Title
- [x] - 슬라이스 하여 뒤로가기 기능
- [x] - 게시물 글자 300자 제한하기
